version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${TIMEZONE:-Europe/Rome}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/local-files:/files
    networks:
      - n8n-network
    depends_on:
      - mongodb
      - ollama

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-changeme}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-n8n_db}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - n8n-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - n8n-network

  express-server:
    image: node:20
    container_name: express-server
    restart: unless-stopped
    working_dir: /usr/src/app
    build: 
      context: ./backend/server
    volumes:
      - ./express-app:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    networks:
      - n8n-network
    depends_on:
      - mongodb

volumes:
  n8n_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  ollama_data:
    driver: local

networks:
  n8n-network:
    driver: bridge
